/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'client-list': RouteRecordInfo<'client-list', '/client/list', Record<never, never>, Record<never, never>>,
    'configuration-categories': RouteRecordInfo<'configuration-categories', '/configuration/categories', Record<never, never>, Record<never, never>>,
    'configuration-providers': RouteRecordInfo<'configuration-providers', '/configuration/providers', Record<never, never>, Record<never, never>>,
    'configuration-sucursales': RouteRecordInfo<'configuration-sucursales', '/configuration/sucursales', Record<never, never>, Record<never, never>>,
    'configuration-units': RouteRecordInfo<'configuration-units', '/configuration/units', Record<never, never>, Record<never, never>>,
    'configuration-warehouses': RouteRecordInfo<'configuration-warehouses', '/configuration/warehouses', Record<never, never>, Record<never, never>>,
    'conversion-list': RouteRecordInfo<'conversion-list', '/conversion/list', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'kardex': RouteRecordInfo<'kardex', '/kardex', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'product-add': RouteRecordInfo<'product-add', '/product/add', Record<never, never>, Record<never, never>>,
    'product-edit-id': RouteRecordInfo<'product-edit-id', '/product/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'product-list': RouteRecordInfo<'product-list', '/product/list', Record<never, never>, Record<never, never>>,
    'products': RouteRecordInfo<'products', '/products', Record<never, never>, Record<never, never>>,
    'purchase-add': RouteRecordInfo<'purchase-add', '/purchase/add', Record<never, never>, Record<never, never>>,
    'purchase-edit-id': RouteRecordInfo<'purchase-edit-id', '/purchase/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'purchase-list': RouteRecordInfo<'purchase-list', '/purchase/list', Record<never, never>, Record<never, never>>,
    'refound-list': RouteRecordInfo<'refound-list', '/refound/list', Record<never, never>, Record<never, never>>,
    'roles-permisos': RouteRecordInfo<'roles-permisos', '/roles-permisos', Record<never, never>, Record<never, never>>,
    'sales-add': RouteRecordInfo<'sales-add', '/sales/add', Record<never, never>, Record<never, never>>,
    'sales-edit-id': RouteRecordInfo<'sales-edit-id', '/sales/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'sales-list': RouteRecordInfo<'sales-list', '/sales/list', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'transport-add': RouteRecordInfo<'transport-add', '/transport/add', Record<never, never>, Record<never, never>>,
    'transport-edit-id': RouteRecordInfo<'transport-edit-id', '/transport/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'transport-list': RouteRecordInfo<'transport-list', '/transport/list', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
  }
}
